# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuavars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='pin',
            field=models.CharField(choices=[('0', 'Patilla 0'), ('1', 'Patilla 1'), ('2', 'Patilla 2'), ('3', 'Patilla 3'), ('4', 'Patilla 4'), ('5', 'Patilla 5'), ('6', 'Patilla 6'), ('7', 'Patilla 7'), ('8', 'Patilla 8'), ('9', 'Patilla 9'), ('10', 'Patilla 10'), ('11', 'Patilla 11'), ('12', 'Patilla 12'), ('13', 'Patilla 13')], max_length=2),
        ),
        migrations.AlterField(
            model_name='relay',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Encendido'),
        ),
    ]
