# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcuavars', '0005_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AddField(
            model_name='relay',
            name='dev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opcuavars.Device', verbose_name='Dispositivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='dev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opcuavars.Device', verbose_name='Dispositivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_type',
            field=models.CharField(choices=[('a', 'Arduino'), ('r', 'Raspberry')], max_length=1, verbose_name='Tipo'),
        ),
    ]
